#!/bin/bash

curl -s --location \
--request GET 'https://betternight.com/service/v1/message/rescue/email?pwd=J3$gqpK9vwf4'



pipeline {
    agent any

    stages {
        stage('test') {
            steps {
                sh label: '', script: '''#!/bin/bash
                    curl -s --location --request GET "https://betternight.com/service/v1/message/rescue/email?pwd=J3$gqpK9vwf4"
                '''
            }
        }
    }
}